# Generated by Django 5.1.4 on 2025-01-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_image', models.ImageField(blank=True, null=True, upload_to='charts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
